# Generated by Django 4.0.1 on 2022-01-25 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.AlterModelOptions(
            name='techcategory',
            options={'verbose_name': 'Tech Category', 'verbose_name_plural': 'Tech Categories'},
        ),
    ]
