# Generated by Django 4.0.1 on 2022-06-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='link',
            new_name='git_link',
        ),
        migrations.AddField(
            model_name='project',
            name='web_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
