# Generated by Django 4.0.1 on 2022-01-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('img_source', models.URLField(blank=True, null=True)),
                ('apps', models.ManyToManyField(blank=True, related_name='apps', to='projects.Project')),
            ],
        ),
    ]
