# Generated by Django 4.0.1 on 2022-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='screen',
            options={'ordering': ['index']},
        ),
        migrations.AddField(
            model_name='screen',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='screen',
            constraint=models.UniqueConstraint(fields=('id', 'index'), name='unique_index'),
        ),
    ]
