# Generated by Django 4.0.1 on 2022-01-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0002_alter_screen_options_screen_index_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='screen',
            name='unique_index',
        ),
        migrations.AlterField(
            model_name='screen',
            name='index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
