# Generated by Django 4.0.1 on 2022-06-15 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0004_screen_background_color_screen_body_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='screen',
            old_name='img_source',
            new_name='bg_img_source',
        ),
        migrations.AddField(
            model_name='screen',
            name='img_1_source',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screen',
            name='img_2_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
