# Generated by Django 4.0.1 on 2022-06-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screens', '0005_rename_img_source_screen_bg_img_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screen',
            name='video_source',
            field=models.URLField(blank=True, null=True),
        ),
    ]
